// Generates supabase/seed.sql from src/data/mock.js — single source of truth.
// Run:  node scripts/gen-seed.mjs
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { clinic, doctor, kpis, schedule, queue, wards, admissions, apptPresentation } from '../src/data/mock.js'

const __dir = dirname(fileURLToPath(import.meta.url))
const out = resolve(__dir, '../supabase/seed.sql')

// ── SQL value helpers ────────────────────────────────────────────
const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`)
const n = (v) => (v === null || v === undefined ? 'null' : Number(v))
const b = (v) => (v ? 'true' : 'false')
const arr = (a) => (!a || !a.length ? `'{}'` : `array[${a.map(q).join(',')}]`)
const json = (o) => `'${JSON.stringify(o).replace(/'/g, "''")}'::jsonb`

const lines = []
const w = (s = '') => lines.push(s)

w('-- AUTO-GENERATED by scripts/gen-seed.mjs — do not edit by hand.')
w('-- 재생성:  node scripts/gen-seed.mjs')
w('begin;')
w('truncate clinics, doctors, patients, queue_entries, safety_assessments,')
w('  rating_scales, trend_points, labs, prescriptions, clinical_notes,')
w('  patient_detail_meta, appointments, kpis, wards, admissions restart identity cascade;')
w()

// clinic + doctor
w(`insert into clinics (hospital, department, room, session, display_date) values`)
w(`  (${q(clinic.hospital)}, ${q(clinic.department)}, ${q(clinic.room)}, ${q(clinic.session)}, ${q(clinic.date)});`)
w()
w(`insert into doctors (name, title, ext_id, initial) values`)
w(`  (${q(doctor.name)}, ${q(doctor.title)}, ${q(doctor.id)}, ${q(doctor.initial)});`)
w()

// kpis
w(`insert into kpis (sort, tone, label, value, sub, delta, delta_tone) values`)
w(
  kpis
    .map((k, i) => `  (${i}, ${q(k.tone)}, ${q(k.label)}, ${q(k.value)}, ${q(k.sub)}, ${q(k.delta ?? null)}, ${q(k.deltaTone ?? null)})`)
    .join(',\n') + ';'
)
w()

// appointments (status = 단일 소스, 표현은 파생)
w(`insert into appointments (sort, start_time, patient_name, description, status, bar, badge_cls, badge_label, tail, is_now) values`)
w(
  schedule.slots
    .map((s, i) => {
      const pr = apptPresentation(s.status, s.now)
      return `  (${i}, ${q(s.time)}, ${q(s.name)}, ${q(s.desc)}, ${q(s.status)}, ${q(pr.bar)}, ${q(pr.badgeCls ?? null)}, ${q(pr.badgeLabel ?? null)}, ${q(pr.tail ?? null)}, ${b(s.now)})`
    })
    .join(',\n') + ';'
)
w()

// wards
w(`insert into wards (sort, code, name, total_beds) values`)
w(wards.map((wd, i) => `  (${i}, ${q(wd.code)}, ${q(wd.name)}, ${n(wd.total_beds)})`).join(',\n') + ';')
w()

// admissions (attending = 시드 의사)
w(`insert into admissions (sort, ward_id, attending_id, patient_name, sex, age, chart_no, room, bed, legal_status, status, dx, admitted_on, day_no, acuity, memo) values`)
w(
  admissions
    .map(
      (a, i) =>
        `  (${i}, (select id from wards where code=${q(a.ward)}), (select id from doctors order by ext_id limit 1), ${q(a.name)}, ${q(a.sex)}, ${n(a.age)}, ${q(a.chart)}, ${q(a.room)}, ${q(a.bed)}, ${q(a.legal)}, ${q(a.status)}, ${q(a.dx)}, ${q(a.admittedOn)}, ${n(a.dayNo)}, ${q(a.acuity)}, ${q(a.memo)})`
    )
    .join(',\n') + ';'
)
w()

// patients + queue + per-patient clinical data, keyed by chart_no
for (let i = 0; i < queue.length; i++) {
  const p = queue[i]
  const d = p.detail
  const pid = `(select id from patients where chart_no = ${q(p.chart)})`
  w(`-- ── ${p.name} (${p.chart}) ──`)
  w(`insert into patients (chart_no, name, sex, age, rrn, initial, primary_tags, attending_id) values`)
  w(`  (${q(p.chart)}, ${q(p.name)}, ${q(p.sex)}, ${n(p.age)}, ${q(p.rrn)}, ${q(p.initial)}, ${arr(p.tags)}, (select id from doctors order by ext_id limit 1));`)

  w(`insert into queue_entries (patient_id, position, no, visit_type, status, status_cls, dx, received, wait, risk) values`)
  w(`  (${pid}, ${i}, ${q(p.no)}, ${q(p.type)}, ${q(p.status)}, ${q(p.statusCls)}, ${q(p.dx)}, ${q(p.received)}, ${q(p.wait)}, ${q(p.risk)});`)

  w(`insert into safety_assessments (patient_id, level, sev, bold, body) values`)
  w(`  (${pid}, ${q(d.safety.level)}, ${q(d.safety.sev)}, ${q(d.safety.bold)}, ${q(d.safety.text)});`)

  w(`insert into patient_detail_meta (patient_id, summary, rx_warn_title, rx_warn_body) values`)
  w(`  (${pid}, ${q(d.summary)}, ${q(d.rx.warn.title)}, ${q(d.rx.warn.text)});`)

  w(`insert into rating_scales (patient_id, sort, name, tag, value, max, pct, severity, severity_label) values`)
  w(
    d.scales
      .map((s, j) => `  (${pid}, ${j}, ${q(s.name)}, ${q(s.tag)}, ${n(s.value)}, ${n(s.max)}, ${n(s.pct)}, ${q(s.cls)}, ${q(s.label)})`)
      .join(',\n') + ';'
  )

  w(`insert into trend_points (patient_id, sort, label, phq, gad) values`)
  w(
    d.trend.labels
      .map((lab, j) => `  (${pid}, ${j}, ${q(lab)}, ${n(d.trend.phq[j])}, ${n(d.trend.gad[j])})`)
      .join(',\n') + ';'
  )

  // labs: flatten groups, preserve order
  const labRows = []
  d.labs.forEach((g) => g.rows.forEach((r) => labRows.push({ group: g.group, ...r })))
  w(`insert into labs (patient_id, sort, lab_group, name, value, ref_range, flag, flag_type, collected) values`)
  w(
    labRows
      .map((r, j) => `  (${pid}, ${j}, ${q(r.group)}, ${q(r.name)}, ${q(r.val)}, ${q(r.ref)}, ${q(r.flag)}, ${q(r.flagType)}, ${q(r.date ?? '06/22')})`)
      .join(',\n') + ';'
  )

  w(`insert into prescriptions (patient_id, sort, drug_class, class_warn, name, brand, dose, sub, sub_bold, qty, price, is_new) values`)
  w(
    d.rx.items
      .map(
        (r, j) =>
          `  (${pid}, ${j}, ${q(r.klass)}, ${b(r.klassWarn)}, ${q(r.name)}, ${q(r.brand ?? '')}, ${q(r.dose)}, ${q(r.sub ?? '')}, ${q(r.subBold ?? '')}, ${q(r.qty ?? '')}, ${q(r.price ?? '')}, ${b(r.isNew)})`
      )
      .join(',\n') + ';'
  )

  w(`insert into clinical_notes (patient_id, sort, author, dept, noted_at, segments) values`)
  w(
    d.notes
      .map((nt, j) => `  (${pid}, ${j}, ${q(nt.author)}, ${q(nt.dept)}, ${q(nt.datetime)}, ${json(nt.segments)})`)
      .join(',\n') + ';'
  )
  w()
}

w('commit;')

writeFileSync(out, lines.join('\n') + '\n', 'utf8')
console.log(`✓ seed written → ${out}  (${lines.length} lines)`)
